// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokRRATnlPSoCFQHaOAxm1bNM8I3gvw5o',
    appId: '1:528417292636:android:0341e8f92ef3e9b2f68199',
    messagingSenderId: '528417292636',
    projectId: 'note-4649a',
    storageBucket: 'note-4649a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGIsentrWPPh2jxfFlucbVnEDXuOQz2fU',
    appId: '1:528417292636:ios:500dbc5713f77a06f68199',
    messagingSenderId: '528417292636',
    projectId: 'note-4649a',
    storageBucket: 'note-4649a.firebasestorage.app',
    androidClientId: '528417292636-am1pocb3tjas8iqs2md25cli91ofeu93.apps.googleusercontent.com',
    iosClientId: '528417292636-9c8hg7notpms069j1rf003iiu4tgvto3.apps.googleusercontent.com',
    iosBundleId: 'com.project.namvox.noteApp',
  );

}